import { render, screen } from '@testing-library/react';
import { Project } from '../../../types';
import ProjectCard from './ProjectCard';

const mockProject: Project = {
  id: 0,
  node_id: '',
  name: 'project title',
  full_name: '',
  private: false,
  owner: undefined,
  html_url: '',
  description: '',
  fork: false,
  url: '',
  forks_url: '',
  keys_url: '',
  collaborators_url: '',
  teams_url: '',
  hooks_url: '',
  issue_events_url: '',
  events_url: '',
  assignees_url: '',
  branches_url: '',
  tags_url: '',
  blobs_url: '',
  git_tags_url: '',
  git_refs_url: '',
  trees_url: '',
  statuses_url: '',
  languages_url: '',
  stargazers_url: '',
  contributors_url: '',
  subscribers_url: '',
  subscription_url: '',
  commits_url: '',
  git_commits_url: '',
  comments_url: '',
  issue_comment_url: '',
  contents_url: '',
  compare_url: '',
  merges_url: '',
  archive_url: '',
  downloads_url: '',
  issues_url: '',
  pulls_url: '',
  milestones_url: '',
  notifications_url: '',
  labels_url: '',
  releases_url: '',
  deployments_url: '',
  created_at: '',
  updated_at: '',
  pushed_at: '',
  git_url: '',
  ssh_url: '',
  clone_url: '',
  svn_url: '',
  homepage: '',
  size: 0,
  stargazers_count: 0,
  watchers_count: 0,
  has_issues: false,
  has_projects: false,
  has_downloads: false,
  has_wiki: false,
  has_pages: false,
  forks_count: 0,
  archived: false,
  disabled: false,
  open_issues_count: 0,
  license: undefined,
  forks: 0,
  open_issues: 0,
  watchers: 0,
  default_branch: ''
};

test('renders the card title', () => {
  render(<ProjectCard project={mockProject} languageColor={"000000ff"} />);
  const titleElement = screen.getByText(/project title/i);
  expect(titleElement).toBeInTheDocument();
});
